import 'package:base/presentation/provider/base_change_notifier.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:interior_design/presentation/provider/call_tracker/call_tracker_provider.dart';
import 'package:interior_design/presentation/provider/call_tracker/dashboard_filter_provider.dart';
import 'package:interior_design/presentation/provider/call_tracker/service_details_support_request/service_details_support_request_provider.dart';
import 'package:interior_design/presentation/provider/call_tracker/service_support_request/view_service_support_request_provider.dart';
import 'package:interior_design/presentation/provider/call_tracker/ticket_dashboard/service_tasks_provider.dart';
import 'package:interior_design/presentation/provider/material_chart_provider/additional_material_chart_main_provider.dart';
import 'package:interior_design/presentation/provider/material_chart_provider/additional_material_detail_provider.dart';
import 'package:interior_design/presentation/provider/material_chart_provider/material_chart_provider.dart';
import 'package:interior_design/presentation/provider/add_observation/add_observation_provider.dart';
import 'package:interior_design/presentation/provider/all_observation_support_request/all_observation_request_provider.dart';
import 'package:interior_design/presentation/provider/all_support_request_provider/all_support_request_provider.dart';
import 'package:interior_design/presentation/provider/close_observation/close_observation_provider.dart';
import 'package:interior_design/presentation/provider/add_support_request/add_support_request_provider.dart';
import 'package:interior_design/presentation/provider/close_support_request/close_support_request_provider.dart';
import 'package:interior_design/presentation/provider/common_support/base_support_provider.dart';
import 'package:interior_design/presentation/provider/dashboard/dashboard_provider.dart';
import 'package:interior_design/presentation/provider/login_and_splash/login_provider.dart';
import 'package:interior_design/presentation/provider/my_observation/my_observation_provider.dart';
import 'package:interior_design/presentation/provider/my_support/my_support_provider.dart';
import 'package:interior_design/presentation/provider/notification_history/notification_history_provider.dart';
import 'package:interior_design/presentation/provider/profile/profile_provider.dart';
import 'package:interior_design/presentation/provider/project_dash_baord/project_dashboard_provider.dart';
import 'package:interior_design/presentation/provider/project_details/project_details_provider.dart';
import 'package:interior_design/presentation/provider/project_location/project_location_provider.dart';
import 'package:interior_design/presentation/provider/project_schedule/graph_based_support_provider.dart';
import 'package:interior_design/presentation/provider/project_schedule/project_schedule_labour_count_provider.dart';
import 'package:interior_design/presentation/provider/project_schedule/project_schedule_provider.dart';
import 'package:interior_design/presentation/provider/project_schedule/project_schedule_status_based_provider.dart';
import 'package:interior_design/presentation/provider/project_schedule/project_schedule_group_activity_provider.dart';
import 'package:interior_design/presentation/provider/project_schedule/task_based_graph_provider.dart';
import 'package:interior_design/presentation/provider/project_schedule_dashboard/project_schedule_dashboard_provider.dart';
import 'package:interior_design/presentation/provider/view_observation_provider/view_observation_provider.dart';
import 'package:interior_design/presentation/provider/view_support_request/view_support_request_provider.dart';

import 'MOM/add_mom_provider.dart';
import 'MOM/mom_list_provider.dart';
import 'call_tracker/add_service_request_provider.dart';
import 'call_tracker/from_home/tasks_wise_ticket_provider.dart';
import 'call_tracker/providers/reassign_enginner_provider.dart';
import 'call_tracker/providers/service_request_dashboard_provider.dart';
import 'call_tracker/providers/service_tasks_provider.dart';
import 'call_tracker/service_request_dashboard_provider.dart';
import 'call_tracker/service_tasks_provider.dart';
import 'call_tracker/service_support_request/service_support_request_provider.dart';
import 'home/home_provider.dart';
import 'home/side_bar_provider.dart';
import 'image_grid_provider/image_grid_provider.dart' show ImageGridProvider;
import 'material_chart_provider/add_additional_material_provider.dart';
import 'my_schedule/my_schedule_provider.dart';
import 'call_tracker/service_ticket_dashboard_provider.dart';
import 'call_tracker/service_details_landing_provider.dart';
import 'package:dcc_module/dcc_module.dart';



final loginProvider = baseChangeNotifier<LoginProvider>(() => LoginProvider());
final projectDetailsProvider = baseChangeNotifier<ProjectDetailsProvider>(() => ProjectDetailsProvider());
final homeProvider = baseChangeNotifierKeepAlive<HomeProvider>(() => HomeProvider());

final addObservationProvider = baseChangeNotifier<AddObservationProvider>(() => AddObservationProvider());
final closeObservationProvider = baseChangeNotifier<CloseObservationProvider>(() => CloseObservationProvider());
final addSupportRequestProvider = baseChangeNotifier<AddSupportRequestProvider>(() => AddSupportRequestProvider());
final baseSupportProvider = baseChangeNotifier<BaseSupportProvider>(() => BaseSupportProvider());
final closeSupportRequestProvider = baseChangeNotifier<CloseSupportRequestProvider>(() => CloseSupportRequestProvider());
final dashBoardProvider = baseChangeNotifier<DashBoardProvider>(() => DashBoardProvider());
final profileProvider = baseChangeNotifier<ProfileProvider>(() => ProfileProvider());
final myObservationProvider = baseChangeNotifier<MyObservationProvider>(() => MyObservationProvider());
final mySupportProvider = baseChangeNotifier<MySupportProvider>(() => MySupportProvider());
final viewObservationProvider = baseChangeNotifier<ViewObservationProvider>(() => ViewObservationProvider());
final viewSupportRequestProvider = baseChangeNotifier<ViewSupportRequestProvider>(() => ViewSupportRequestProvider());
final allObservationRequestProvider = baseChangeNotifier<AllObservationRequestProvider>(() => AllObservationRequestProvider());
final allSupportRequestProvider = baseChangeNotifierKeepAlive<AllSupportRequestProvider>(() => AllSupportRequestProvider());
final projectScheduleDashBoardProvider = baseChangeNotifier<ProjectScheduleDashBoardProvider>(() => ProjectScheduleDashBoardProvider());
final myScheduleProvider = baseChangeNotifier<MyScheduleProvider>(() => MyScheduleProvider());
final projectScheduleProvider = baseChangeNotifier<ProjectScheduleProvider>(() => ProjectScheduleProvider());
final projectTasksStatusBased = baseChangeNotifier<ProjectTasksStatusBased>(() => ProjectTasksStatusBased());
final taskBasedGraphProvider = baseChangeNotifier<TaskBasedGraphProvider>(() => TaskBasedGraphProvider());
final imageGridProvider = baseChangeNotifier<ImageGridProvider>(() => ImageGridProvider());
final projectLocationProvider = baseChangeNotifier<ProjectLocationProvider>(() => ProjectLocationProvider());
final sideBarProvider = baseChangeNotifier<SideBarProvider>(() => SideBarProvider());
final graphBasedSupportProvider = baseChangeNotifier<GraphBasedSupportProvider>(() => GraphBasedSupportProvider());
final materialChartProvider = baseChangeNotifier<MaterialChartProvider>(() => MaterialChartProvider());
final projectDashboardProvider = baseChangeNotifierKeepAlive<ProjectDashboardProvider>(() => ProjectDashboardProvider());
final additionalMaterialChartProvider = baseChangeNotifier<AdditionalMaterialChartProvider>(() => AdditionalMaterialChartProvider());
final additionalMaterialMainProvider = baseChangeNotifier<AdditionalMaterialMainProvider>(() => AdditionalMaterialMainProvider());
final callTrackerProvider = baseChangeNotifierKeepAlive<CallTrackerProvider>(() => CallTrackerProvider());
final addServiceRequestProvider = baseChangeNotifierKeepAlive<AddServiceRequestProvider>(() => AddServiceRequestProvider());
final serviceRequestDashboardProvider = baseChangeNotifierKeepAlive<ServiceRequestDashboardProvider>(() => ServiceRequestDashboardProvider());
final serviceTasksProvider = baseChangeNotifier<ServiceTasksProvider>(() => ServiceTasksProvider());
final serviceSupportRequestSiteWiseProvider = baseChangeNotifier<ServiceSupportRequestSiteWiseProvider>(() => ServiceSupportRequestSiteWiseProvider());
final serviceDetailsSupportRequestProvider = baseChangeNotifierKeepAlive<ServiceDetailsSupportRequestProvider>(() => ServiceDetailsSupportRequestProvider());
final viewServiceSupportRequestProvider = baseChangeNotifier<ViewServiceSupportRequestProvider>(() => ViewServiceSupportRequestProvider());
final additionalMaterialDetailProvider = baseChangeNotifier<AdditionalMaterialDetailProvider>(() => AdditionalMaterialDetailProvider());
final notificationHistoryProvider = baseChangeNotifier<NotificationHistoryProvider>(() => NotificationHistoryProvider());
final serviceTicketDashboardProvider = baseChangeNotifierKeepAlive<ServiceTicketDashboardProvider>(() => ServiceTicketDashboardProvider());
final serviceDetailsLandingProvider = baseChangeNotifierKeepAlive<ServiceDetailsLandingProvider>(() => ServiceDetailsLandingProvider());
final reassignEngineerProvider = baseChangeNotifier<ReassignEngineerProvider>(() => ReassignEngineerProvider());
final serviceTasksListProvider = baseChangeNotifierKeepAlive<ServiceTasksListProvider>(() => ServiceTasksListProvider());
final tasksWiseTicketProvider = baseChangeNotifierKeepAlive<TasksWiseTicketProvider>(() => TasksWiseTicketProvider());
final dashboardFilterProvider = baseChangeNotifierKeepAlive<DashboardFilterProvider>(() => DashboardFilterProvider());
final projectScheduleGroupActivityProvider = baseChangeNotifier<ProjectScheduleGroupActivityProvider>(() => ProjectScheduleGroupActivityProvider());
final projectScheduleLabourCountProvider = baseChangeNotifier<ProjectScheduleLabourCountProvider>(() => ProjectScheduleLabourCountProvider());
final addMOMProvider = baseChangeNotifier<AddMOMProvider>(() => AddMOMProvider());
final momListProvider = baseChangeNotifier<MOMListProvider>(() => MOMListProvider());